# Site settings
title: Konstantin Shenderov - Test Automation & Full Stack Developer
email: shenderov.k@gmail.com
description: >-
  Konstantin Shenderov is a Test Automation Engineer and Full Stack Developer with over 12 years of experience in software testing, QA automation, and web development.
baseurl: "" 
url: "https://shenderov.me"

# Build settings
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
sass:
  sass_dir: _sass

uglifier: false

minify_html:
  enable: false

assets:
  compress:
    js: false
    css: false
    extensions: ['.css', '.js']
  autoprefixer: false

# Plugins
plugins:
  - jekyll-assets